### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by xtmgah** [mcmero/SVclone#1]
Hello:

We are trying to using SVclone do some analyses. thanks for developing this software, it's very useful. Do you have any docker version? We have some issue to install it. it's have the following error, do you have any idea? Thanks. 

zhangt8@cn3241:/data/zhangt8/Ref/SVclone/SVclone$ SVclone.py -h
Traceback (most recent call last):
  File "/usr/local/apps/svclone/0.2.2-13-ge402c3f/SVclone.py", line 7, in <module>
    from SVclone import run_filter
  File "/usr/local/apps/svclone/0.2.2-13-ge402c3f/SVclone/run_filter.py", line 15, in <module>
    from . import run_clus
  File "/usr/local/apps/svclone/0.2.2-13-ge402c3f/SVclone/run_clus.py", line 25, in <module>
    from . import cluster
  File "/usr/local/apps/svclone/0.2.2-13-ge402c3f/SVclone/cluster.py", line 8, in <module>
    from sklearn.cluster import KMeans
  File "/home/zhangt8/.local/lib/python2.7/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/home/zhangt8/.local/lib/python2.7/site-packages/sklearn/cluster/spectral.py", line 17, in <module>
    from ..manifold import spectral_embedding
  File "/home/zhangt8/.local/lib/python2.7/site-packages/sklearn/manifold/__init__.py", line 8, in <module>
    from .spectral_embedding_ import SpectralEmbedding, spectral_embedding
  File "/home/zhangt8/.local/lib/python2.7/site-packages/sklearn/manifold/spectral_embedding_.py", line 12, in <module>
    from scipy.sparse.linalg.eigen.lobpcg.lobpcg import symeig
ImportError: cannot import name symeig

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by mcmero** [comment]
Thank you for reporting this and sorry about the late reply. The clustering code has changed significantly and no longer requires scikitlearn, so the bug you reported should no longer occur. We currently do not have a docker version, but will consider one for the future.
