### ISSUE TITLE
installation//import problem

### ISSUE THREAD

**Issue by EricDeveaud** [mcmero/SVclone#4]
Hello 

trying to install SVclone.
what I did

```
/local/gensoft2/adm/Python/2.7/bin/python2.7 -m virtualenv /local/gensoft2/exe/SVclone/0.4.0/venv
git clone https://github.com/mcmero/SVclone.git
cd SVclone 
.  /local/gensoft2/exe/SVclone/0.4.0/venv/bin/activate
pip install -r requirements.txt
python setup.py install 
Rscript install_R_requirements.R
```

and then tried to run SVclone.py. but:
```
(venv) [gensoft@e211aa82115c SVclone-0.4.0]$ SVclone.py -h 
Traceback (most recent call last):
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/bin/SVclone.py", line 4, in <module>
    __import__('pkg_resources').run_script('SVclone==0.2.1', 'SVclone.py')
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/SVclone-0.2.1-py2.7.egg/EGG-INFO/scripts/SVclone.py", line 7, in <module>
    from SVclone import run_filter
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/bin/SVclone.py", line 4, in <module>
    __import__('pkg_resources').run_script('SVclone==0.2.1', 'SVclone.py')
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/local/gensoft2/exe/SVclone/0.4.0/venv/lib/python2.7/site-packages/SVclone-0.2.1-py2.7.egg/EGG-INFO/scripts/SVclone.py", line 7, in <module>
    from SVclone import run_filter
ImportError: cannot import name run_filter
```

same problem with the 0.4.0 archive (https://github.com/mcmero/SVclone/archive/v0.4.0.tar.gz)

best regards

Eric

**Comment by mcmero** [comment]
Hi Eric,

Did you receive any error messages when running `python setup.py install`? Also try running `python SVclone.py -h`. Are you able to run the `./run_example.sh` script without the error?

If these suggestions don't work, I would also try installing with Python 3 using the latest code in the master branch, or the v1.0.0 release. The Python 2 version will be deprecated in future releases.

Cheers,
Marek
