### ISSUE TITLE
Error :  No section: 'BamParameters'

### ISSUE THREAD

**Issue by KeyTals** [mcmero/SVclone#5]
Hi , I am getting following error at annotate stage.

SVclone.py annotate  -cfg config.ini -i simple.txt -b tumor.bam -s test --sv_format simple

Traceback (most recent call last):
  File "/mnt/nasapps/development/python/anaconda3/bin/SVclone.py", line 4, in <module>
    __import__('pkg_resources').run_script('SVclone==0.2.1', 'SVclone.py')
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/site-packages/SVclone-0.2.1-py3.7.egg/EGG-INFO/scripts/SVclone.py", line 163, in <module>
    args.func(args)
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/site-packages/SVclone-0.2.1-py3.7.egg/Sclone/SVprocess/annotate.py", line 512, in preproc_svs
    max_cn       = float(Config.get('BamParameters', 'max_cn'))
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/mnt/nasapps/development/python/anaconda3/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'BamParameters'

The bam fie is already indexed and i was able to validate the bam file.

Keyur

**Comment by mcmero** [comment]
Hi Keyur,

Please double check your config.ini file--it should have a section labelled `[BamParameters]` at the top. If not, make sure this section is present. See the default `svclone_config.ini` for details of which sections and parameters are required.

Cheers,
Marek
